<?xml version="1.0" encoding="UTF-8"?>
<project name="SorveteriaTropicalzinCremoso_Etapa4" default="default" basedir=".">
    <description>Projeto Integrador - Etapa 4 - Integração MySQL - Sorveteria Tropicalzin Cremoso</description>
    
    <path id="classpath">
        <fileset dir="lib" includes="*.jar"/>
    </path>
    
    <target name="default" depends="compile">
        <echo message="Projeto Etapa 4 compilado com sucesso!"/>
    </target>
    
    <target name="init">
        <mkdir dir="build/classes"/>
        <mkdir dir="dist"/>
    </target>
    
    <target name="compile" depends="init">
        <javac srcdir="src" destdir="build/classes" classpathref="classpath" includeantruntime="false" encoding="UTF-8" source="17" target="17"/>
    </target>
    
    <target name="jar" depends="compile">
        <jar destfile="dist/SorveteriaTropicalzinCremoso_Etapa4.jar" basedir="build/classes">
            <manifest>
                <attribute name="Main-Class" value="com.sorveteria.Principal"/>
                <attribute name="Class-Path" value="lib/mysql-connector-j-8.0.33.jar"/>
            </manifest>
        </jar>
    </target>
    
    <target name="run" depends="jar">
        <java jar="dist/SorveteriaTropicalzinCremoso_Etapa4.jar" fork="true"/>
    </target>
</project>
